{
    "作者": "🐰兔爷🐇",
    "站名": "xiaoxintv",
    "编码": "UTF-8",
    "请求头": "User-Agent$MOBILE_UA",
    "主页url": "https://xiaoxintv.cc/index.php",
    "首页": "100",
    "起始页": "1",
    "分类url": "/vod/show/area/{area}/by/{by}/class/{class}/id/{cateId}/lang/{lang}/letter/{letter}/page/{catePg}/year/{year}.html",
    "分类": "电视剧&电影&动漫&综艺&短剧",
    "分类值": "6&7&5&3&64",
    "数组": "默认--post\">&&</a||首页--<article&&</a||短剧--<div class=\"s6&&</a",
    "图片": "data-original=\"&&\"",
    "标题": "title=\"&&\"",
    "副标题": "默认--text\">&&</div||首页--text*\">&&</div",
    "链接": "href=\"&&\"",
    "影片年代": "/year/*.html\">&&</a",
    "影片地区": "/area/*.html\">&&</a",
    "影片类型": "scroll no-margin\">&&</a",
    "状态": "更新:&&</p",
    "导演": "導演:&&</p",
    "主演": "主演:&&</p",
    "简介": "宝盒提醒:请不要相信视频内的广告!剧情👉-+right-align\">&&</p",
    "线路数组": "<span class=\"max&&/span>",
    "线路标题": ">&&<",
    "播放数组": "<li class=\"*active&&</div",
    "播放列表": "<a&&/a>",
    "播放标题": ">&&<",
    "跳转播放链接": "file:\"&&\"",
    "搜索请求头": "User-Agent$MOBILE_UA",
    "搜索模式": "1",
    "搜索url": "/vod/search.html?wd={wd}&page={pg}",
    "搜索数组": "<item>&&</item>",
    "搜索标题": "<title>&&</title>[替换: *>>空]",
    "搜索图片": "<link>&&</link>",
    "搜索副标题": "<title>&&</title>[替换:* >>空]",
    "搜索链接": "<link>&&</link>",
    "跳转搜索图片": "lazyload\"*data-src=\"&&\"",
    "筛选": "1",
    "类型": ""
}
